/**
 * The "AI-generated, pending physician review" signal.
 *
 * This is one component used everywhere that state appears, on purpose. If each
 * screen styled its own disclaimer, the label would read as legal boilerplate
 * that varies by context; kept identical, it becomes a status indicator the user
 * learns to read at a glance — and its absence becomes meaningful too, which is
 * what makes the `reviewed` variant worth anything.
 *
 * The violet (`draft`) is reserved for this state and used nowhere else in the
 * palette.
 */

function DraftGlyph({ className = '' }) {
  return (
    <svg
      viewBox="0 0 12 12"
      aria-hidden="true"
      className={`h-2.5 w-2.5 shrink-0 ${className}`}
      fill="none"
    >
      <circle cx="6" cy="6" r="5" stroke="currentColor" strokeWidth="1.5" strokeDasharray="2.4 2" />
    </svg>
  )
}

function CheckGlyph({ className = '' }) {
  return (
    <svg
      viewBox="0 0 12 12"
      aria-hidden="true"
      className={`h-2.5 w-2.5 shrink-0 ${className}`}
      fill="none"
    >
      <path
        d="M2 6.4 4.6 9 10 3.2"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

/**
 * @param {object} props
 * @param {'pending' | 'reviewed'} [props.state]
 * @param {'inline' | 'block'} [props.size]
 */
export function AiDraftBadge({ state = 'pending', size = 'inline', className = '' }) {
  const reviewed = state === 'reviewed'

  const label = reviewed ? 'Physician reviewed' : 'AI draft · pending physician review'
  const shortLabel = reviewed ? 'Physician reviewed' : 'AI draft · pending review'

  const tone = reviewed
    ? 'border-verified/30 bg-verified-wash text-verified'
    : 'border-draft/30 bg-draft-wash text-draft-deep'

  if (size === 'block') {
    return (
      <div
        className={`flex items-start gap-3 rounded-md border px-4 py-3 ${tone} ${className}`}
      >
        {reviewed ? <CheckGlyph className="mt-1" /> : <DraftGlyph className="mt-1" />}
        <div>
          <p className="font-mono text-[10px] uppercase tracking-label">{label}</p>
          <p className="mt-1 text-[13px] leading-snug opacity-90">
            {reviewed
              ? 'A licensed physician reviewed, edited, and approved this response. It is not a substitute for in-person care.'
              : 'Generated by AI from the submitted intake. Not a diagnosis and not medical advice until a licensed physician has reviewed it.'}
          </p>
        </div>
      </div>
    )
  }

  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-mono text-[10px] uppercase tracking-label ${tone} ${className}`}
    >
      {reviewed ? <CheckGlyph /> : <DraftGlyph />}
      <span className="hidden sm:inline">{label}</span>
      <span className="sm:hidden">{shortLabel}</span>
    </span>
  )
}
